[2023-05-11T11:54:44.800+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T11:53:46.096507+00:00/task_id=upload_to_mongodb_task permission to 509
[2023-05-11T11:54:44.908+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T11:53:46.096507+00:00/task_id=upload_to_mongodb_task permission to 509
[2023-05-11T11:54:45.007+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_processing.upload_to_mongodb_task manual__2023-05-11T11:53:46.096507+00:00 [queued]>
[2023-05-11T11:54:45.040+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_processing.upload_to_mongodb_task manual__2023-05-11T11:53:46.096507+00:00 [queued]>
[2023-05-11T11:54:45.041+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-11T11:54:45.122+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): upload_to_mongodb_task> on 2023-05-11 11:53:46.096507+00:00
[2023-05-11T11:54:45.131+0000] {standard_task_runner.py:57} INFO - Started process 707 to run task
[2023-05-11T11:54:45.136+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tiktok_processing', 'upload_to_mongodb_task', 'manual__2023-05-11T11:53:46.096507+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/task_7_1.py', '--cfg-path', '/tmp/tmpd0s85tuw']
[2023-05-11T11:54:45.140+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask upload_to_mongodb_task
[2023-05-11T11:54:45.201+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-05-11T11:54:45.268+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T11:53:46.096507+00:00/task_id=upload_to_mongodb_task permission to 509
[2023-05-11T11:54:45.272+0000] {task_command.py:410} INFO - Running <TaskInstance: tiktok_processing.upload_to_mongodb_task manual__2023-05-11T11:53:46.096507+00:00 [running]> on host c77c354ecf4a
[2023-05-11T11:54:45.861+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiktok_processing' AIRFLOW_CTX_TASK_ID='upload_to_mongodb_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T11:53:46.096507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-11T11:53:46.096507+00:00'
[2023-05-11T11:54:45.893+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task_7_1.py", line 49, in upload_to_mongodb
    mongo_conn = MongoHook(mongo_conn_id="mongo_conn")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mongo/hooks/mongo.py", line 56, in __init__
    self.connection = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mongo_default` isn't defined
[2023-05-11T11:54:45.966+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=tiktok_processing, task_id=upload_to_mongodb_task, execution_date=20230511T115346, start_date=20230511T115445, end_date=20230511T115445
[2023-05-11T11:54:46.312+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 27 for task upload_to_mongodb_task (The conn_id `mongo_default` isn't defined; 707)
[2023-05-11T11:54:46.355+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-11T11:54:46.382+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
