[2023-05-11T13:52:21.892+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T13:45:40.512849+00:00/task_id=data_processing_tasks.clean_content_column_task permission to 509
[2023-05-11T13:52:25.872+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T13:45:40.512849+00:00/task_id=data_processing_tasks.clean_content_column_task permission to 509
[2023-05-11T13:52:28.536+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_processing.data_processing_tasks.clean_content_column_task manual__2023-05-11T13:45:40.512849+00:00 [queued]>
[2023-05-11T13:52:29.709+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_processing.data_processing_tasks.clean_content_column_task manual__2023-05-11T13:45:40.512849+00:00 [queued]>
[2023-05-11T13:52:29.710+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-11T13:52:29.925+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): data_processing_tasks.clean_content_column_task> on 2023-05-11 13:45:40.512849+00:00
[2023-05-11T13:52:38.317+0000] {standard_task_runner.py:57} INFO - Started process 3146 to run task
[2023-05-11T13:52:58.962+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tiktok_processing', 'data_processing_tasks.clean_content_column_task', 'manual__2023-05-11T13:45:40.512849+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/task_7_1.py', '--cfg-path', '/tmp/tmp7672e7e7']
[2023-05-11T13:53:03.847+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask data_processing_tasks.clean_content_column_task
[2023-05-11T13:53:22.857+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-05-11T13:54:14.363+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T13:45:40.512849+00:00/task_id=data_processing_tasks.clean_content_column_task permission to 509
[2023-05-11T13:54:14.981+0000] {task_command.py:410} INFO - Running <TaskInstance: tiktok_processing.data_processing_tasks.clean_content_column_task manual__2023-05-11T13:45:40.512849+00:00 [running]> on host d8f273d8514c
[2023-05-11T13:54:17.829+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiktok_processing' AIRFLOW_CTX_TASK_ID='data_processing_tasks.clean_content_column_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T13:45:40.512849+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-11T13:45:40.512849+00:00'
[2023-05-11T13:54:19.131+0000] {local_task_job_runner.py:122} ERROR - Received SIGTERM. Terminating subprocesses
[2023-05-11T13:54:19.205+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 3146. PIDs of all processes in the group: [3146]
[2023-05-11T13:54:19.273+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 3146
[2023-05-11T13:54:19.288+0000] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-11T13:54:19.354+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task_7_1.py", line 40, in clean_content_column
    df = pd.read_csv("/opt/airflow/data/sorted_tiktok_without_nulls.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-05-11T13:54:19.470+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=tiktok_processing, task_id=data_processing_tasks.clean_content_column_task, execution_date=20230511T134540, start_date=20230511T135229, end_date=20230511T135419
[2023-05-11T13:54:19.685+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 50 for task data_processing_tasks.clean_content_column_task (Task received SIGTERM signal; 3146)
[2023-05-11T13:54:19.767+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3146, status='terminated', exitcode=1, started='13:52:30') (3146) terminated with exit code 1
[2023-05-11T13:54:19.769+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 143
[2023-05-11T13:54:19.870+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
