[2023-05-11T13:47:54.612+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T13:45:40.512849+00:00/task_id=data_processing_tasks.replace_null_values_task permission to 509
[2023-05-11T13:47:54.807+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T13:45:40.512849+00:00/task_id=data_processing_tasks.replace_null_values_task permission to 509
[2023-05-11T13:47:54.930+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_processing.data_processing_tasks.replace_null_values_task manual__2023-05-11T13:45:40.512849+00:00 [None]>
[2023-05-11T13:47:54.952+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_processing.data_processing_tasks.replace_null_values_task manual__2023-05-11T13:45:40.512849+00:00 [None]>
[2023-05-11T13:47:54.953+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-11T13:47:55.129+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): data_processing_tasks.replace_null_values_task> on 2023-05-11 13:45:40.512849+00:00
[2023-05-11T13:47:55.136+0000] {standard_task_runner.py:57} INFO - Started process 3102 to run task
[2023-05-11T13:47:55.142+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tiktok_processing', 'data_processing_tasks.replace_null_values_task', 'manual__2023-05-11T13:45:40.512849+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/task_7_1.py', '--cfg-path', '/tmp/tmp_uzbhv32']
[2023-05-11T13:47:55.153+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask data_processing_tasks.replace_null_values_task
[2023-05-11T13:47:55.200+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-05-11T13:47:55.334+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T13:45:40.512849+00:00/task_id=data_processing_tasks.replace_null_values_task permission to 509
[2023-05-11T13:47:55.347+0000] {task_command.py:410} INFO - Running <TaskInstance: tiktok_processing.data_processing_tasks.replace_null_values_task manual__2023-05-11T13:45:40.512849+00:00 [running]> on host d8f273d8514c
[2023-05-11T13:47:55.623+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiktok_processing' AIRFLOW_CTX_TASK_ID='data_processing_tasks.replace_null_values_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T13:45:40.512849+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-11T13:45:40.512849+00:00'
[2023-05-11T13:54:11.129+0000] {local_task_job_runner.py:299} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-05-11T13:54:11.626+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 3102. PIDs of all processes in the group: [3102]
[2023-05-11T13:54:11.799+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 3102
[2023-05-11T13:54:12.075+0000] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-11T13:54:12.991+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task_7_1.py", line 26, in replace_null_values
    df.to_csv(output_file_path, index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 257, in save
    self._save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 262, in _save
    self._save_body()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 300, in _save_body
    self._save_chunk(start_i, end_i)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 316, in _save_chunk
    self.writer,
  File "pandas/_libs/writers.pyx", line 72, in pandas._libs.writers.write_csv_rows
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1542, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-05-11T13:54:13.281+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=tiktok_processing, task_id=data_processing_tasks.replace_null_values_task, execution_date=20230511T134540, start_date=20230511T134754, end_date=20230511T135413
[2023-05-11T13:54:13.979+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 49 for task data_processing_tasks.replace_null_values_task (Task received SIGTERM signal; 3102)
[2023-05-11T13:54:14.333+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3102, status='terminated', exitcode=1, started='13:47:54') (3102) terminated with exit code 1
